- hosts: all
  tasks:
    - name: "Install httpd"
      package:
       name: "httpd"
       state: present

    - name: "Create File"
      copy:
       dest: "/var/www/html/index.html"
       content: "<br> <h2> This is created by ansible </h2> <br>"

    - name: "Start Services"
      service:
       name: "httpd"
       state: restarted
       enabled: yes